version: '3.1'

services:

  db:
    container_name: sanote-db
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  api:
    container_name: sanote-api
    build: .
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_HOST: db
      MONGO_PORT: 27017